// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfiSKpQuCf7eyWVorlyUEgpk2w-8WSfik',
    appId: '1:555376241232:web:bacd00f28234f4f2563f55',
    messagingSenderId: '555376241232',
    projectId: 'skill-swap-app-xyz',
    authDomain: 'skill-swap-app-xyz.firebaseapp.com',
    storageBucket: 'skill-swap-app-xyz.firebasestorage.app',
    measurementId: 'G-PMVJ4JL1XR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0MKtl686tDEUZRr9mY6o219txfSGVjrc',
    appId: '1:555376241232:android:0056d6950ac5bcd9563f55',
    messagingSenderId: '555376241232',
    projectId: 'skill-swap-app-xyz',
    storageBucket: 'skill-swap-app-xyz.firebasestorage.app',
  );
}
